import Foundation

extension Chord2 {
    public static var C = Chord2(.C, type: .majorTriad)
    public static var D = Chord2(.D, type: .majorTriad)
    public static var E = Chord2(.E, type: .majorTriad)
    public static var F = Chord2(.F, type: .majorTriad)
    public static var G = Chord2(.G, type: .majorTriad)
    public static var A = Chord2(.A, type: .majorTriad)
    public static var B = Chord2(.B, type: .majorTriad)

    public static var Cm = Chord2(.C, type: .minorTriad)
    public static var Dm = Chord2(.D, type: .minorTriad)
    public static var Em = Chord2(.E, type: .minorTriad)
    public static var Fm = Chord2(.F, type: .minorTriad)
    public static var Gm = Chord2(.G, type: .minorTriad)
    public static var Am = Chord2(.A, type: .minorTriad)
    public static var Bm = Chord2(.B, type: .minorTriad)

    public static var Cdim = Chord2(.C, type: .diminishedTriad)
    public static var Ddim = Chord2(.D, type: .diminishedTriad)
    public static var Edim = Chord2(.E, type: .diminishedTriad)
    public static var Fdim = Chord2(.F, type: .diminishedTriad)
    public static var Gdim = Chord2(.G, type: .diminishedTriad)
    public static var Adim = Chord2(.A, type: .diminishedTriad)
    public static var Bdim = Chord2(.B, type: .diminishedTriad)

    public static var Caug = Chord2(.C, type: .augmentedTriad)
    public static var Daug = Chord2(.D, type: .augmentedTriad)
    public static var Eaug = Chord2(.E, type: .augmentedTriad)
    public static var Faug = Chord2(.F, type: .augmentedTriad)
    public static var Gaug = Chord2(.G, type: .augmentedTriad)
    public static var Aaug = Chord2(.A, type: .augmentedTriad)
    public static var Baug = Chord2(.B, type: .augmentedTriad)

    public static var Cs = Chord2(.Cs, type: .majorTriad)
    public static var Ds = Chord2(.Ds, type: .majorTriad)
    public static var Es = Chord2(.Es, type: .majorTriad)
    public static var Fs = Chord2(.Fs, type: .majorTriad)
    public static var Gs = Chord2(.Gs, type: .majorTriad)
    public static var As = Chord2(.As, type: .majorTriad)
    public static var Bs = Chord2(.Bs, type: .majorTriad)

    public static var Csm = Chord2(.Cs, type: .minorTriad)
    public static var Dsm = Chord2(.Ds, type: .minorTriad)
    public static var Esm = Chord2(.Es, type: .minorTriad)
    public static var Fsm = Chord2(.Fs, type: .minorTriad)
    public static var Gsm = Chord2(.Gs, type: .minorTriad)
    public static var Asm = Chord2(.As, type: .minorTriad)
    public static var Bsm = Chord2(.Bs, type: .minorTriad)

    public static var Csdim = Chord2(.Cs, type: .diminishedTriad)
    public static var Dsdim = Chord2(.Ds, type: .diminishedTriad)
    public static var Esdim = Chord2(.Es, type: .diminishedTriad)
    public static var Fsdim = Chord2(.Fs, type: .diminishedTriad)
    public static var Gsdim = Chord2(.Gs, type: .diminishedTriad)
    public static var Asdim = Chord2(.As, type: .diminishedTriad)
    public static var Bsdim = Chord2(.Bs, type: .diminishedTriad)

    public static var Cb = Chord2(.Cb, type: .majorTriad)
    public static var Db = Chord2(.Db, type: .majorTriad)
    public static var Eb = Chord2(.Eb, type: .majorTriad)
    public static var Fb = Chord2(.Fb, type: .majorTriad)
    public static var Gb = Chord2(.Gb, type: .majorTriad)
    public static var Ab = Chord2(.Ab, type: .majorTriad)
    public static var Bb = Chord2(.Bb, type: .majorTriad)

    public static var Cbm = Chord2(.Cb, type: .minorTriad)
    public static var Dbm = Chord2(.Db, type: .minorTriad)
    public static var Ebm = Chord2(.Eb, type: .minorTriad)
    public static var Fbm = Chord2(.Fb, type: .minorTriad)
    public static var Gbm = Chord2(.Gb, type: .minorTriad)
    public static var Abm = Chord2(.Ab, type: .minorTriad)
    public static var Bbm = Chord2(.Bb, type: .minorTriad)

    public static var Cbdim = Chord2(.Cb, type: .diminishedTriad)
    public static var Dbdim = Chord2(.Db, type: .diminishedTriad)
    public static var Ebdim = Chord2(.Eb, type: .diminishedTriad)
    public static var Fbdim = Chord2(.Fb, type: .diminishedTriad)
    public static var Gbdim = Chord2(.Gb, type: .diminishedTriad)
    public static var Abdim = Chord2(.Ab, type: .diminishedTriad)
    public static var Bbdim = Chord2(.Bb, type: .diminishedTriad)
}
