import Foundation

extension Key {
    public static let Cb = Key(root: NoteClass(.C, accidental: .flat), scale: .major)
    public static let Gb = Key(root: NoteClass(.G, accidental: .flat), scale: .major)
    public static let Db = Key(root: NoteClass(.D, accidental: .flat), scale: .major)
    public static let Ab = Key(root: NoteClass(.A, accidental: .flat), scale: .major)
    public static let Eb = Key(root: NoteClass(.E, accidental: .flat), scale: .major)
    public static let Bb = Key(root: NoteClass(.B, accidental: .flat), scale: .major)
    public static let F = Key(root: NoteClass(.F), scale: .major)
    public static let C = Key(root: NoteClass(.C), scale: .major)
    public static let G = Key(root: NoteClass(.G), scale: .major)
    public static let D = Key(root: NoteClass(.D), scale: .major)
    public static let A = Key(root: NoteClass(.A), scale: .major)
    public static let E = Key(root: NoteClass(.E), scale: .major)
    public static let B = Key(root: NoteClass(.B), scale: .major)
    public static let Fs = Key(root: NoteClass(.F, accidental: .sharp), scale: .major)
    public static let Cs = Key(root: NoteClass(.C, accidental: .sharp), scale: .major)

    public static let ab = Key(root: NoteClass(.A, accidental: .flat), scale: .minor)
    public static let eb = Key(root: NoteClass(.E, accidental: .flat), scale: .minor)
    public static let bb = Key(root: NoteClass(.B, accidental: .flat), scale: .minor)
    public static let f = Key(root: NoteClass(.F), scale: .minor)
    public static let c = Key(root: NoteClass(.C), scale: .minor)
    public static let g = Key(root: NoteClass(.G), scale: .minor)
    public static let d = Key(root: NoteClass(.D), scale: .minor)
    public static let a = Key(root: NoteClass(.A), scale: .minor)
    public static let e = Key(root: NoteClass(.E), scale: .minor)
    public static let b = Key(root: NoteClass(.B), scale: .minor)
    public static let fs = Key(root: NoteClass(.F, accidental: .sharp), scale: .minor)
    public static let cs = Key(root: NoteClass(.C, accidental: .sharp), scale: .minor)
    public static let gs = Key(root: NoteClass(.G, accidental: .sharp), scale: .minor)
    public static let ds = Key(root: NoteClass(.D, accidental: .sharp), scale: .minor)
    public static let `as` = Key(root: NoteClass(.A, accidental: .sharp), scale: .minor)

    public static let Abm = Key(root: NoteClass(.A, accidental: .flat), scale: .minor)
    public static let Ebm = Key(root: NoteClass(.E, accidental: .flat), scale: .minor)
    public static let Bbm = Key(root: NoteClass(.B, accidental: .flat), scale: .minor)
    public static let Fm = Key(root: NoteClass(.F), scale: .minor)
    public static let Cm = Key(root: NoteClass(.C), scale: .minor)
    public static let Gm = Key(root: NoteClass(.G), scale: .minor)
    public static let Dm = Key(root: NoteClass(.D), scale: .minor)
    public static let Am = Key(root: NoteClass(.A), scale: .minor)
    public static let Em = Key(root: NoteClass(.E), scale: .minor)
    public static let Bm = Key(root: NoteClass(.B), scale: .minor)
    public static let Fsm = Key(root: NoteClass(.F, accidental: .sharp), scale: .minor)
    public static let Csm = Key(root: NoteClass(.C, accidental: .sharp), scale: .minor)
    public static let Gsm = Key(root: NoteClass(.G, accidental: .sharp), scale: .minor)
    public static let Dsm = Key(root: NoteClass(.D, accidental: .sharp), scale: .minor)
    public static let Asm = Key(root: NoteClass(.A, accidental: .sharp), scale: .minor)
}
