import Foundation

public extension Key {
    static let Cb = Key(root: NoteClass(.C, accidental: .flat), scale: .major)
    static let Gb = Key(root: NoteClass(.G, accidental: .flat), scale: .major)
    static let Db = Key(root: NoteClass(.D, accidental: .flat), scale: .major)
    static let Ab = Key(root: NoteClass(.A, accidental: .flat), scale: .major)
    static let Eb = Key(root: NoteClass(.E, accidental: .flat), scale: .major)
    static let Bb = Key(root: NoteClass(.B, accidental: .flat), scale: .major)
    static let F = Key(root: NoteClass(.F), scale: .major)
    static let C = Key(root: NoteClass(.C), scale: .major)
    static let G = Key(root: NoteClass(.G), scale: .major)
    static let D = Key(root: NoteClass(.D), scale: .major)
    static let A = Key(root: NoteClass(.A), scale: .major)
    static let E = Key(root: NoteClass(.E), scale: .major)
    static let B = Key(root: NoteClass(.B), scale: .major)
    static let Fs = Key(root: NoteClass(.F, accidental: .sharp), scale: .major)
    static let Cs = Key(root: NoteClass(.C, accidental: .sharp), scale: .major)

    static let ab = Key(root: NoteClass(.A, accidental: .flat), scale: .minor)
    static let eb = Key(root: NoteClass(.E, accidental: .flat), scale: .minor)
    static let bb = Key(root: NoteClass(.B, accidental: .flat), scale: .minor)
    static let f = Key(root: NoteClass(.F), scale: .minor)
    static let c = Key(root: NoteClass(.C), scale: .minor)
    static let g = Key(root: NoteClass(.G), scale: .minor)
    static let d = Key(root: NoteClass(.D), scale: .minor)
    static let a = Key(root: NoteClass(.A), scale: .minor)
    static let e = Key(root: NoteClass(.E), scale: .minor)
    static let b = Key(root: NoteClass(.B), scale: .minor)
    static let fs = Key(root: NoteClass(.F, accidental: .sharp), scale: .minor)
    static let cs = Key(root: NoteClass(.C, accidental: .sharp), scale: .minor)
    static let gs = Key(root: NoteClass(.G, accidental: .sharp), scale: .minor)
    static let ds = Key(root: NoteClass(.D, accidental: .sharp), scale: .minor)
    static let `as` = Key(root: NoteClass(.A, accidental: .sharp), scale: .minor)

    static let Abm = Key(root: NoteClass(.A, accidental: .flat), scale: .minor)
    static let Ebm = Key(root: NoteClass(.E, accidental: .flat), scale: .minor)
    static let Bbm = Key(root: NoteClass(.B, accidental: .flat), scale: .minor)
    static let Fm = Key(root: NoteClass(.F), scale: .minor)
    static let Cm = Key(root: NoteClass(.C), scale: .minor)
    static let Gm = Key(root: NoteClass(.G), scale: .minor)
    static let Dm = Key(root: NoteClass(.D), scale: .minor)
    static let Am = Key(root: NoteClass(.A), scale: .minor)
    static let Em = Key(root: NoteClass(.E), scale: .minor)
    static let Bm = Key(root: NoteClass(.B), scale: .minor)
    static let Fsm = Key(root: NoteClass(.F, accidental: .sharp), scale: .minor)
    static let Csm = Key(root: NoteClass(.C, accidental: .sharp), scale: .minor)
    static let Gsm = Key(root: NoteClass(.G, accidental: .sharp), scale: .minor)
    static let Dsm = Key(root: NoteClass(.D, accidental: .sharp), scale: .minor)
    static let Asm = Key(root: NoteClass(.A, accidental: .sharp), scale: .minor)
}
