name: CI

on: [push, pull_request]
env:
  XCODE_VER: 13.1

jobs:
  build:
    strategy:
      matrix:
        xcode_version: ['13.1']
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out Tonic 
        uses: actions/checkout@v2
      - name: Test tonic 
        run: |
          set -euo pipefail
          swift test

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Swift on Linux
        uses: sersoft-gmbh/swifty-linux-action@v2
      - name: Check out Tonic 
        uses: actions/checkout@v2
      - name: Test tonic 
        run: |
          set -euo pipefail
          swift test
